parameters:
  db.class: AppBundle\Db\Db

  database.db1.dsn: pgsql:host=127.0.0.1;port=5432;dbname=testdb
  database.db1.username: username
  database.db1.password: password

services:
  db1:
    class: %db.class%
    calls:
      - [setDsn, [%database.db1.dsn%]]
      - [setUsername, [%database.db1.username%]]
      - [setPassword, [%database.db1.password%]]