admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

usuario:
    resource: "@UsuarioBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

root:
   path: /
   defaults:
      _controller: FrameworkBundle:Redirect:urlRedirect
      path: /usuario/login
      permanent: true