<?php

namespace SigepBundle\Repository;

/**
 * SigepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SigepRepository extends \Doctrine\ORM\EntityRepository
{
}
